Set the database encoding as UTF8
jamesnunn/pgtest pull request #22
Opened 2020-02-19 16:57 UTC by RangelReale

In my Brazilian Portuguese application, using accented characters was giving unicode errors on save using pgtest. It looks like that for some reason, the database wasn't being created with the usual UTF8 encoding. A parameter is need for pg_ctl to ensure this, so I added it. I think this should not influence other users.

2020-02-19 18:23 UTC, ltalirz requested changes
Hi @RangelReale , thanks for your contribution!

If I understand correctly, then what you are changing here is only the *default* encoding of the database, while the actual encoding can be specified separately for every table you create (e.g. in my use case, we are also using utf8 encoding but setting it for every table explicitly).

At the moment, your PR changes the default encoding of the postgres installation to a hardcoded value and I'm not sure your assumption 

> I think this should not influence other users.

is valid.

I would be fine to accept a PR that adds a `default_encoding` kwarg to `PGTest` (which also becomes a class attribute).
If  the argument is not set, then, by default, no encoding should be specified.

2020-02-19 18:23 UTC, ltalirz commented on pgtest/pgtest.py
> +                       'trust -E UTF8"').format(pg_ctl=self._pg_ctl_exe,
```suggestion
                       'trust --encoding UTF8"').format(pg_ctl=self._pg_ctl_exe,
```

2020-02-19 18:44 UTC, RangelReale commented
Done, I tested with --encoding and it worked.

2020-02-21 15:56 UTC, ltalirz requested changes
@RangelReale Sorry for the late reply - had zero free time over the last days

Your changes look good to me - please also add a test [here](https://github.com/jamesnunn/pgtest/blob/master/test/test.py#L48).
At minimum, the test should pass 'UTF8' to the default_encoding argument of the constructor.

In principle it would also be nice to test whether the default of the DB is indeed set as expected. Not sure whether there is an easy way to do this, and ok to merge without this if there isn't.

2023-10-16 16:06 UTC, closed without merging